# Generated by Django 5.2.7 on 2025-11-01 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('registr_no', models.IntegerField(primary_key=True, serialize=False)),
                ('itu_mail', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('registration_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'personel',
            },
        ),
        migrations.CreateModel(
            name='LanguageCompensationScore',
            fields=[
                ('lang_comp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('letter_score', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'language_compensation_score',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('tc_no', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('mid_name', models.CharField(blank=True, max_length=255, null=True)),
                ('surname', models.CharField(max_length=255)),
                ('personal_mail', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('registr_no', models.IntegerField()),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('prom_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('next_date', models.DateField()),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'promotion',
            },
        ),
        migrations.CreateModel(
            name='AcademicPersonel',
            fields=[
                ('registr_no', models.OneToOneField(db_column='registr_no', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainpage_app.personel')),
                ('duty_type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'academic_personel',
            },
        ),
        migrations.CreateModel(
            name='ManagementStaff',
            fields=[
                ('registr_no', models.OneToOneField(db_column='registr_no', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainpage_app.personel')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'management_staff',
            },
        ),
        migrations.CreateModel(
            name='SystemAdmin',
            fields=[
                ('registr_no', models.OneToOneField(db_column='registr_no', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainpage_app.personel')),
                ('user_name', models.CharField(max_length=255)),
                ('encrypted_password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'system_admin',
            },
        ),
        migrations.CreateModel(
            name='LowAcademic',
            fields=[
                ('registr_no', models.OneToOneField(db_column='registr_no', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainpage_app.academicpersonel')),
                ('last_duty_ext_date', models.DateField()),
            ],
            options={
                'db_table': 'low_academic',
            },
        ),
        migrations.CreateModel(
            name='PersonelGetsLangCompensScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('lang_comp_id', models.ForeignKey(db_column='lang_comp_id', on_delete=django.db.models.deletion.CASCADE, to='mainpage_app.languagecompensationscore')),
                ('registr_no', models.ForeignKey(db_column='registr_no', on_delete=django.db.models.deletion.CASCADE, to='mainpage_app.personel')),
            ],
            options={
                'db_table': 'personel_gets_langcompensscore',
                'unique_together': {('registr_no', 'date')},
            },
        ),
        migrations.CreateModel(
            name='HighAcademicGetsScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_date', models.DateField()),
                ('score_type', models.CharField(max_length=50)),
                ('registr_no', models.ForeignKey(db_column='registr_no', on_delete=django.db.models.deletion.CASCADE, to='mainpage_app.academicpersonel')),
            ],
            options={
                'db_table': 'high_academic_gets_score',
                'unique_together': {('registr_no', 'score_date')},
            },
        ),
        migrations.CreateModel(
            name='ManagementStaffGetsProm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prom_id', models.ForeignKey(db_column='prom_id', on_delete=django.db.models.deletion.CASCADE, to='mainpage_app.promotion')),
                ('registr_no', models.ForeignKey(db_column='registr_no', on_delete=django.db.models.deletion.CASCADE, to='mainpage_app.managementstaff')),
            ],
            options={
                'db_table': 'management_staff_gets_prom',
                'unique_together': {('registr_no', 'prom_id')},
            },
        ),
        migrations.CreateModel(
            name='LowAcademicDutyExtends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_date', models.DateField()),
                ('next_ext_date', models.DateField()),
                ('registr_no', models.ForeignKey(db_column='registr_no', on_delete=django.db.models.deletion.CASCADE, to='mainpage_app.lowacademic')),
            ],
            options={
                'db_table': 'low_academic_duty_extends',
                'unique_together': {('registr_no', 'ext_date')},
            },
        ),
    ]
