# Generated by Django 5.2.7 on 2025-11-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage_app', '0002_alter_academicpersonel_registr_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='tc_no',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
