# Generated by Django 5.2.7 on 2025-11-04 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage_app', '0003_alter_person_tc_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='registr_no',
            field=models.OneToOneField(blank=True, db_column='registr_no', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person', to='mainpage_app.personel'),
        ),
    ]
