# Generated by Django 5.2.7 on 2025-11-04 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage_app', '0004_alter_person_registr_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='registr_no',
        ),
        migrations.RemoveField(
            model_name='personel',
            name='registr_no',
        ),
        migrations.AddField(
            model_name='personel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='personel',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainpage_app.person'),
        ),
        migrations.AlterField(
            model_name='academicpersonel',
            name='registr_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='academic_personel', serialize=False, to='mainpage_app.personel'),
        ),
        migrations.AlterField(
            model_name='highacademicgetsscore',
            name='registr_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='high_scores', to='mainpage_app.academicpersonel'),
        ),
        migrations.AlterField(
            model_name='lowacademic',
            name='registr_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='low_academic', serialize=False, to='mainpage_app.academicpersonel'),
        ),
        migrations.AlterField(
            model_name='lowacademicdutyextends',
            name='registr_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_extends', to='mainpage_app.lowacademic'),
        ),
        migrations.AlterField(
            model_name='managementstaff',
            name='registr_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='management_staff', serialize=False, to='mainpage_app.personel'),
        ),
        migrations.AlterField(
            model_name='managementstaffgetsprom',
            name='prom_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_staffs', to='mainpage_app.promotion'),
        ),
        migrations.AlterField(
            model_name='managementstaffgetsprom',
            name='registr_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='mainpage_app.managementstaff'),
        ),
        migrations.AlterField(
            model_name='personelgetslangcompensscore',
            name='lang_comp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personel_scores', to='mainpage_app.languagecompensationscore'),
        ),
        migrations.AlterField(
            model_name='personelgetslangcompensscore',
            name='registr_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lang_scores', to='mainpage_app.personel'),
        ),
        migrations.AlterField(
            model_name='systemadmin',
            name='registr_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='system_admin', serialize=False, to='mainpage_app.personel'),
        ),
    ]
