# Generated by Django 5.2.7 on 2025-11-04 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage_app', '0005_remove_person_registr_no_remove_personel_registr_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementstaffgetsprom',
            name='prom_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage_app.promotion'),
        ),
    ]
